name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        # python -m pip install --upgrade pip
        # pip install -r requirements.txt
        pip install sonar-scanner

    - name: Run SonarQube Scanner
      run: |
        sonar-scanner \
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
          -Dsonar.host.url=https://codeanalysis.dhwaniris.in \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.python.version=3.9
